"""create github_events table

Revision ID: 328fa6c6970a
Revises: f3724901e86e
Create Date: 2026-06-11 19:08:41.580759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328fa6c6970a'
down_revision: Union[str, Sequence[str], None] = 'f3724901e86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_events', sa.Column('event_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_github_events_event_id'), 'github_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_events_event_id'), table_name='github_events')
    op.drop_column('github_events', 'event_id')
    # ### end Alembic commands ###
