"""create github_events table

Revision ID: f3724901e86e
Revises: 
Create Date: 2026-06-11 17:37:06.287977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3724901e86e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_events_created_at'), 'github_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_github_events_event_type'), 'github_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_github_events_repo_name'), 'github_events', ['repo_name'], unique=False)
    op.create_index(op.f('ix_github_events_username'), 'github_events', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_events_username'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_repo_name'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_event_type'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_created_at'), table_name='github_events')
    op.drop_table('github_events')
    # ### end Alembic commands ###
